arch:
  - amd64
  - ppc64le

language: erlang

otp_release:
  - 22.0
  - 21.3
  - 20.3
  - 19.3

before_install:
  - sudo apt-get -y install dcmtk

install:
  - pip install --user --disable-pip-version-check codecov
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

jobs:
  include:
    - otp_release: 19.3
      arch: s390x
  exclude:
    - otp_release: 19.3
      arch: ppc64le

script:
  - lscpu | grep Endian
  - ./rebar3 compile
  - ./rebar3 edoc
  - ./rebar3 xref
  - ./rebar3 eunit --cover
  - ./rebar3 proper --cover
  - ./rebar3 ct --cover --readable=false
  - ./rebar3 cover
  - ./rebar3 codecov analyze

after_success:
    codecov
