@startuml
left to right direction
skinparam packageStyle rectangle

package Stockholm {
actor "Stockholm Client" as S_CLIENT
agent "Stockholm PACS" as S_PACS
}

package Berlin {
actor "Berlin Client" as B_CLIENT
agent "Berlin PACS" as B_PACS
}

package Helsinki {
actor "Helsinki Client" as H_CLIENT
agent "Helsinki PACS" as H_PACS
}

cloud {

component "WolfPACS" as WP

package "Workers - Type 1" {
	agent "Worker A" as WA
	agent "Worker B" as WB
	agent "Worker C" as WC
}

package "Workers - Type 2"{
	agent "Worker D" as WD
}

note bottom of WP
     Series with the same StudyUID
     will always end up on the same worker.
end note

actor "WolfPACS admin" as ADMIN

note left of ADMIN
     Admin can configure WolfPACS
     over http on port 8080.
end note
}

WP <-[#black]- ADMIN


S_CLIENT -[#blue]- S_PACS

S_PACS -[#blue]-> WP : 1

WP -[#blue]-> WA : 2

WP <-[#blue]- WA : 3

WP -[#blue]-> S_PACS : 4



B_CLIENT -[#green]- B_PACS

B_PACS -[#green]-> WP

WP -[#green]-> WD

WP <-[#green]- WD

WP -[#green]-> B_PACS



H_CLIENT -[#orange]- H_PACS

H_PACS -[#orange]-> WP

WP -[#orange]-> WB

WP <-[#orange]- WB

WP -[#orange]-> H_PACS

@enduml
