@startuml
left to right direction
skinparam packageStyle rectangle

package Stockholm {
actor "Stockholm Client" as S_CLIENT
agent "Stockholm PACS" as S_PACS
}

package Berlin {
actor "Berlin Client" as B_CLIENT
agent "Berlin PACS" as B_PACS
}

cloud {

component "WolfPACS" as WP

agent "Worker A" as WA
agent "Worker B" as WB
agent "Worker C" as WC
}

S_CLIENT --> WP
B_CLIENT --> WP

WP <--> WA
WP <--> WB
WP <--> WC

WP --> S_PACS
WP --> B_PACS

@enduml
