name: CI

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['22.2']
        rebar3: ['3.14.4']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}

      - run: rebar3 compile
      - run: rebar3 edoc
      - run: rebar3 xref
      - run: rebar3 eunit --cover
      - run: rebar3 proper --cover
      - run: rebar3 ct --readable true --cover --readable=false
      - run: rebar3 cover
